# Generated by Django 3.2.7 on 2021-09-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='occupation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='workplace',
            field=models.CharField(max_length=255),
        ),
    ]
