# Generated by Django 3.2.7 on 2021-09-17 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0003_auto_20210917_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='citizenship_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citizen',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
