# Generated by Django 3.2.7 on 2021-09-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0004_auto_20210917_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('sector', models.CharField(choices=[('government', 'Srayarda'), ('technology', 'Dali'), ('commerce', 'Tezara'), ('insurance', 'Krasalma'), ('education', 'Mantra'), ('healthcare', 'Krarupa'), ('manufacturing', 'Busma'), ('mining', 'Ipulsa'), ('construction', 'Cinam'), ('travel', 'Lugrunda')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='citizen',
            name='workplace',
        ),
        migrations.AddField(
            model_name='citizen',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonakista.organisation'),
        ),
    ]
