# Generated by Django 3.2.7 on 2021-09-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0005_auto_20210917_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
