# Generated by Django 3.2.7 on 2021-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0006_alter_city_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=True, help_text='If recent, will this article be visible on the homepage?'),
        ),
        migrations.AddField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=True, help_text='Is this article searchable in the articles page?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(help_text='The main body of the article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(help_text='A short summary of the article for the homepage or article browse page.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='The image to appear with the article', null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='The headline of the article.', max_length=255, verbose_name='Headline'),
        ),
    ]
