# Generated by Django 3.2.7 on 2021-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0008_article_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='action_text',
            field=models.CharField(default='Kalya ami', help_text='The text to appear on the button to see the full article.', max_length=64),
        ),
    ]
