# Generated by Django 3.2.7 on 2021-09-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0009_article_action_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='How this article will appear in URLs (leave blank for auto)', max_length=255),
        ),
    ]
