# Generated by Django 3.2.7 on 2021-09-21 22:25

from django.db import migrations, models
import django.db.models.deletion
import zonakista.models.base.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0010_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('headword', models.CharField(help_text='The dictionary form of the word', max_length=255, unique=True)),
                ('pronunciation', models.CharField(blank=True, help_text='IPA for this word (do not include slashes or brackets)', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, zonakista.models.base.mixins.AutoSlugMixin),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='How this article will appear in URLs (leave blank for auto)', max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partOfSpeech', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('conjunction', 'Conjunction'), ('determiner', 'Determiner'), ('interjection', 'Interjection'), ('preposition', 'Preposition'), ('pronoun', 'Pronoun'), ('proper noun', 'Proper Noun'), ('numeral', 'Numeral')], max_length=64)),
                ('gender', models.CharField(blank=True, choices=[('masculine', 'Masculine'), ('feminine', 'Feminine')], max_length=64)),
                ('wordClass', models.CharField(choices=[('thematic', 'Thematic'), ('athematic', 'Athematic'), ('irregular', 'Irregular'), ('a-stem', 'a-stem'), ('i-stem', 'i-stem'), ('u-stem', 'u-stem'), ('r-stem', 'r-stem')], max_length=64)),
                ('alternative_note', models.CharField(blank=True, help_text='A simple explanation of this alternative, e.g feminine', max_length=255)),
                ('etymology_note', models.CharField(blank=True, help_text='Origin of this word', max_length=255)),
                ('source_language', models.CharField(blank=True, help_text='The language source of this word. Proto-Indo-European must be abbreviated to PIE. Do not use any other abbreviations. Leave blank if the word is derived from existing Vedian words.', max_length=64)),
                ('pie_root', models.CharField(blank=True, help_text='The single PIE root this word stems from, if it is of native Vedian etymology.', max_length=64)),
                ('notes', models.CharField(blank=True, help_text='Any other notes related to this sense.', max_length=255)),
                ('alternative_to', models.ForeignKey(blank=True, help_text='If this word is an alternative form (e.g other gender or colloquial alternative) then include the main word here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternatives', to='zonakista.word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='zonakista.word')),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(help_text='The example sentence in Vedian.', max_length=255)),
                ('gloss', models.CharField(blank=True, help_text='Translation of the example sentence', max_length=255)),
                ('source', models.CharField(blank=True, help_text='If applicable, the source of the example.', max_length=255)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='zonakista.sense')),
            ],
        ),
        migrations.CreateModel(
            name='Derivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derives_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_terms', to='zonakista.sense')),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_terms', to='zonakista.sense')),
            ],
        ),
    ]
