# Generated by Django 3.2.7 on 2021-09-21 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0011_auto_20210921_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='Which order in the sense this gloss should appear')),
                ('field', models.CharField(blank=True, help_text="A defining characteristic of this word or its usage, if applicable, e.g 'biology' or 'colloquial'.", max_length=128)),
                ('gloss', models.CharField(help_text='The actual gloss', max_length=255)),
                ('sense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosses', to='zonakista.sense')),
            ],
            options={
                'verbose_name_plural': 'Glosses',
            },
        ),
        migrations.AddIndex(
            model_name='gloss',
            index=models.Index(fields=['sense', 'index'], name='zonakista_g_sense_i_1cc8b5_idx'),
        ),
    ]
