# Generated by Django 3.2.7 on 2021-09-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonakista', '0013_word_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sense',
            name='wordClass',
            field=models.CharField(blank=True, choices=[('thematic', 'Thematic'), ('athematic', 'Athematic'), ('irregular', 'Irregular'), ('a-stem', 'a-stem'), ('i-stem', 'i-stem'), ('u-stem', 'u-stem'), ('r-stem', 'r-stem')], max_length=64),
        ),
    ]
